apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: enterprise-incident
type: Opaque
stringData:
  POSTGRES_USER: incident_user
  POSTGRES_PASSWORD: incident_password
  POSTGRES_DB: incident_db